---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args:
          - --allow-multiple-document
        # We exclude helm template files since in raw form, they are not valid yaml
        exclude: helm/fiftyone-teams-app/templates
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        # Ignore generated files
        exclude: ^helm/fiftyone-teams-app/values.schema.json
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude_types:
          - go
          - go-mod
          - go-sum
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `helm/fiftyone-teams-app` directory
          - --chart-search-root=helm/fiftyone-teams-app
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
  - repo: https://github.com/dadav/helm-schema
    rev: 0.18.1
    hooks:
      - id: helm-schema
        args:
          - --chart-search-root=./helm/fiftyone-teams-app
          - --no-dependencies
          - --add-schema-reference
          - --skip-auto-generation=additionalProperties,required
          - --append-newline
          # This breaks type annotations
          # - --helm-docs-compatibility-mode

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: helm/local-self-signed-example/cert-manger-crds|tests/go.sum
        args:
          - -L
          # fiftyone.management as fom
          - fom
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        entry: yamllint --config-file .yamllint.yaml
        # We exclude helm template files since in raw form, they are not valid yaml
        exclude: helm/fiftyone-teams-app/templates
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        args:
          - --bullets
          - '-'
          - -i
          - docker/README.md
          - helm/fiftyone-teams-app/README.md.gotmpl
          - helm/README.md
          - CONTRIBUTING.md
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.29
    hooks:
      - id: helmlint
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --exclude-secrets
          - '(password|REPLACEME|fiftyone-teams-tls-secret|3-9XjJ-gUV?vp\^e\(WUk>LD&lAjh7yEji|btv8BiFCaPIayWU3IU3a_Lm_EMIIk-t6H_yN1ORV45o=|5b32118032bfd50b64b3cc7c0e0821f4e84f63ad517a9687ac2b6ce6ab261976|aGM4\?s&t-n;\!\*U96oA#bdo,\+JU\)ac1T7|test-*|/api/proxy/fiftyone-teams|/opt/plugins|fiftyone-license|LICENSE_KEY_FILE_PATHS)'
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
      - id: shfmt
        args:
          - --diff
          - --write
          - --simplify
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
