---
# https://github.com/losisin/helm-values-schema-json/tree/main

# https://json-schema.org/draft/2020-12
draft: 2020

indent: 4

output: helm/fiftyone-teams-app/values.schema.json

# Allow additional properties such as env vars
# and additional maps
noAdditionalProperties: false

useHelmDocs: true

values:
  - helm/fiftyone-teams-app/values.yaml
