---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: license

manifests:
  rawYaml:
    - secret-license.yaml
deploy:
  kubectl:
    defaultNamespace: '{{.FIFTYONE_TEAMS_NAMESPACE | default "fiftyone-teams"}}'
    hooks:
      before:
        - host:
            command: ["sh", "-c", 'kubectl create namespace ${FIFTYONE_TEAMS_NAMESPACE:-"fiftyone-teams"} || true']
  kubeContext: minikube
