---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: license

manifests:
  rawYaml:
    - secret-license.yaml
deploy:
  kubectl:
    defaultNamespace: '{{.FIFTYONE_TEAMS_NAMESPACE | default "fiftyone-teams"}}'
  kubeContext: minikube
