---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mongodb-community-operator-crds

manifests:
  rawYaml:
    # CRDs from chart version `v0.13.0`.
    # When chart's CRDs change, these local files needs to be updated.
    - helm/local-self-signed-example/mongodb-community-operator-crds/*.yaml
deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mongodb-community-operator-namespace

manifests:
  rawYaml:
    - helm/local-self-signed-example/mongodb-namespace.yaml
deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mongodb-community-operator-secrets

manifests:
  rawYaml:
    - helm/local-self-signed-example/mongodb-password.yaml
deploy:
  kubectl: {}

requires:
  - configs:
      - mongodb-community-operator-namespace
---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mongodb

deploy:
  statusCheckDeadlineSeconds: 540
  helm:
    releases:
      - name: mongodb
        remoteChart: mongodb/community-operator
        version: 0.13.0
        createNamespace: true
        namespace: fiftyone-teams-mongodb
        overrides:
          community-operator-crds:
            enabled: false
          createResource: true
          resource:
            name: mongodb-replica-set
            version: 8.0.0
            members: 1
            tls:
              enabled: false
            users:
              - name: root
                db: admin
                passwordSecretRef:
                  name: mongodb-test-root-password
                scramCredentialsSecretName: fiftyone-teams  # pragma: allowlist secret
                roles:
                  - name: clusterAdmin
                    db: admin
                  - name: userAdminAnyDatabase
                    db: admin
                  - name: readWriteAnyDatabase
                    db: admin
                  - name: dbAdminAnyDatabase
                    db: admin
requires:
  - configs:
      - mongodb-community-operator-crds
      - mongodb-community-operator-secrets
      - mongodb-community-operator-namespace
