---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-test-root-password
  namespace: fiftyone-teams-mongodb
type: Opaque
stringData:
  password: "3-9XjJ-gUV?vp^e(WUk>LD&lAjh7yEji"  # pragma: allowlist secret
