---
services:
  fiftyone-app-common:
    image: voxel51/fiftyone-app:v2.11.1
    environment:
      API_URL: ${API_URL}
      FIFTYONE_APP_DEFAULT_QUERY_PERFORMANCE: ${FIFTYONE_APP_DEFAULT_QUERY_PERFORMANCE}
      FIFTYONE_APP_ENABLE_QUERY_PERFORMANCE: ${FIFTYONE_APP_ENABLE_QUERY_PERFORMANCE}
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_DATABASE_ADMIN: false
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
      FIFTYONE_DEFAULT_APP_PORT: 5151
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_MEDIA_CACHE_APP_IMAGES: false
      FIFTYONE_MEDIA_CACHE_SIZE_BYTES: -1
      FIFTYONE_SIGNED_URL_EXPIRATION: ${FIFTYONE_SIGNED_URL_EXPIRATION:-24}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${FIFTYONE_DEFAULT_APP_ADDRESS}:${FIFTYONE_DEFAULT_APP_PORT}:5151
    restart: always

  teams-api-common:
    image: voxel51/fiftyone-teams-api:v2.11.1
    environment:
      API_EXTERNAL_URL: ${FIFTYONE_API_URI}
      CAS_BASE_URL: ${CAS_BASE_URL:-http://teams-cas:3000/cas/api}
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_ENV: ${FIFTYONE_ENV}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_LOGGING_FORMAT: ${FIFTYONE_LOGGING_FORMAT:-text}
      GRAPHQL_DEFAULT_LIMIT: ${GRAPHQL_DEFAULT_LIMIT}
      LOGGING_LEVEL: ${API_LOGGING_LEVEL:-INFO}
      MONGO_DEFAULT_DB: ${FIFTYONE_DATABASE_NAME}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${API_BIND_ADDRESS}:${API_BIND_PORT}:8000
    restart: always

  teams-app-common:
    image: voxel51/fiftyone-teams-app:v2.11.1
    environment:
      API_URL: ${API_URL}
      APP_USE_HTTPS: ${APP_USE_HTTPS:-true}
      FIFTYONE_API_URI: ${FIFTYONE_API_URI:-"Please contact your Admin for an API URI"}
      FIFTYONE_APP_ALLOW_MEDIA_EXPORT: ${FIFTYONE_APP_ALLOW_MEDIA_EXPORT:-true}
      FIFTYONE_APP_TEAMS_SDK_RECOMMENDED_VERSION: 2.11.1
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_SERVER_ADDRESS: ""
      FIFTYONE_SERVER_PATH_PREFIX: /api/proxy/fiftyone-teams
      FIFTYONE_TEAMS_PROXY_URL: ${FIFTYONE_TEAMS_PROXY_URL}
      NODE_ENV: production
      RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
      FIFTYONE_APP_ANONYMOUS_ANALYTICS_ENABLED: ${FIFTYONE_APP_ANONYMOUS_ANALYTICS_ENABLED:-true}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # GLOBAL_AGENT_HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # GLOBAL_AGENT_HTTP_PROXY: ${HTTP_PROXY_URL}
      # GLOBAL_AGENT_NO_PROXY: ${NO_PROXY_LIST}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # ROARR_LOG: false
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${APP_BIND_ADDRESS}:${APP_BIND_PORT}:3000
    restart: always

  teams-cas-common:
    image: voxel51/fiftyone-teams-cas:v2.11.1
    environment:
      CAS_DATABASE_NAME: ${CAS_DATABASE_NAME:-cas}
      CAS_DEFAULT_USER_ROLE: ${CAS_DEFAULT_USER_ROLE:-GUEST}
      CAS_MONGODB_URI: ${CAS_MONGO_DB_URI:-$FIFTYONE_DATABASE_URI}
      DEBUG: ${CAS_DEBUG:-cas:*,-cas:*:debug}
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      LICENSE_KEY_FILE_PATHS: ${LICENSE_KEY_FILE_PATHS:-/opt/fiftyone/licenses/license}
      TEAMS_API_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      TEAMS_API_MONGODB_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # GLOBAL_AGENT_HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # GLOBAL_AGENT_HTTP_PROXY: ${HTTP_PROXY_URL}
      # GLOBAL_AGENT_NO_PROXY: ${NO_PROXY_LIST}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # ROARR_LOG: false
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${CAS_BIND_ADDRESS:-127.0.0.1}:${CAS_BIND_PORT:-3030}:3000
    restart: always
    volumes:
      - type: bind
        source: ${LOCAL_LICENSE_FILE_DIR}
        target: /opt/fiftyone/licenses
        read_only: true

  teams-plugins-common:
    image: voxel51/fiftyone-app-torch:v2.11.1
    environment:
      API_URL: ${API_URL}
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_DATABASE_ADMIN: false
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
      FIFTYONE_DEFAULT_APP_PORT: 5151
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_MEDIA_CACHE_APP_IMAGES: false
      FIFTYONE_MEDIA_CACHE_SIZE_BYTES: -1
      FIFTYONE_PLUGINS_DIR: /opt/plugins
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    restart: always

  teams-do-common:
    image: voxel51/fiftyone-teams-cv-full:v2.11.1
    deploy:
      replicas: ${FIFTYONE_DELEGATED_OPERATOR_WORKER_REPLICAS:-3}
    command: >
      /bin/sh -c "fiftyone delegated launch -t remote"
    environment:
      API_URL: ${API_URL}
      FIFTYONE_DATABASE_ADMIN: false
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_MEDIA_CACHE_SIZE_BYTES: -1
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    restart: always
    volumes:
      - plugins-vol:/opt/plugins:ro
