version: '3.8'
services:
  teams-api:
    image: voxel51/fiftyone-teams-api:v1.2.1
    environment:
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_CLIENT_ID: ${AUTH0_API_CLIENT_ID}
      AUTH0_API_CLIENT_SECRET: ${AUTH0_API_CLIENT_SECRET}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_ENV: ${FIFTYONE_ENV}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_PLUGINS_DIR: /opt/plugins
      GRAPHQL_DEFAULT_LIMIT: ${GRAPHQL_DEFAULT_LIMIT}
      LOGGING_LEVEL: ${API_LOGGING_LEVEL:-INFO}
      MONGO_DEFAULT_DB: ${FIFTYONE_DATABASE_NAME}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then uncomment the environment variables below
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
    ports:
      - ${API_BIND_ADDRESS}:${API_BIND_PORT}:8000
    volumes:
      - plugins-vol:/opt/plugins
  teams-app:
    image: voxel51/fiftyone-teams-app:v1.2.1
    environment:
      API_URL: ${API_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_ORGANIZATION: ${AUTH0_ORGANIZATION}
      AUTH0_SECRET: ${AUTH0_SECRET}
      APP_USE_HTTPS: ${APP_USE_HTTPS:-true}
      FIFTYONE_APP_TEAMS_SDK_RECOMMENDED_VERSION: 0.12.1
      FIFTYONE_SERVER_ADDRESS: ""
      FIFTYONE_SERVER_PATH_PREFIX: /api/proxy/fiftyone-teams
      FIFTYONE_TEAMS_PROXY_URL: ${FIFTYONE_TEAMS_PROXY_URL}
      NODE_ENV: production
      RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then uncomment the environment variables below
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # GLOBAL_AGENT_HTTP_PROXY: ${HTTP_PROXY_URL}
      # GLOBAL_AGENT_HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # GLOBAL_AGENT_NO_PROXY: ${NO_PROXY_LIST}
    ports:
      - ${APP_BIND_ADDRESS}:${APP_BIND_PORT}:3000
  fiftyone-app:
    image: voxel51/fiftyone-app:v1.2.1
    environment:
      API_URL: ${API_URL}
      FIFTYONE_DATABASE_ADMIN: false
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
      FIFTYONE_DEFAULT_APP_PORT: 5151
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_MEDIA_CACHE_IMAGES: false
      FIFTYONE_MEDIA_CACHE_SIZE_BYTES: -1
      FIFTYONE_PLUGINS_DIR: /opt/plugins
      FIFTYONE_TEAMS_AUDIENCE: ${AUTH0_AUDIENCE}
      FIFTYONE_TEAMS_CLIENT_ID: ${AUTH0_CLIENT_ID}
      FIFTYONE_TEAMS_DOMAIN: ${AUTH0_DOMAIN}
      FIFTYONE_TEAMS_ORGANIZATION: ${AUTH0_ORGANIZATION}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then uncomment the environment variables below
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
    ports:
      - ${FIFTYONE_DEFAULT_APP_ADDRESS}:${FIFTYONE_DEFAULT_APP_PORT}:5151
    volumes:
      - plugins-vol:/opt/plugins:ro
volumes:
  plugins-vol:
