---
# For Proxy Server instructions please see
#  https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/docker#environment-proxies
services:
  teams-api:
    extends:
      file: common-services.yaml
      service: teams-api-common
    environment:
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    volumes:
      - plugins-vol:/opt/plugins
  teams-app:
    extends:
      file: common-services.yaml
      service: teams-app-common
  fiftyone-app:
    extends:
      file: common-services.yaml
      service: fiftyone-app-common
    environment:
      FIFTYONE_PLUGINS_CACHE_ENABLED: true
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    volumes:
      - plugins-vol:/opt/plugins:ro
volumes:
  plugins-vol:
