services:
  teams-api:
    extends:
      file: common-services.yaml
      service: teams-api-common
    environment:
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    volumes:
      - plugins-vol:/opt/plugins
  teams-app:
    extends:
      file: common-services.yaml
      service: teams-app-common
    environment:
      FIFTYONE_TEAMS_PLUGIN_URL: ${FIFTYONE_TEAMS_PLUGIN_URL}
  fiftyone-app:
    extends:
      file: common-services.yaml
      service: fiftyone-app-common
  teams-plugins:
    extends:
      file: common-services.yaml
      service: teams-plugins-common
    volumes:
      - plugins-vol:/opt/plugins:ro
volumes:
  plugins-vol:
