---
services:
  fiftyone-app-common:
    image: voxel51/fiftyone-app:v1.6.0
    environment:
      API_URL: ${API_URL}
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_DATABASE_ADMIN: false
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
      FIFTYONE_DEFAULT_APP_PORT: 5151
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_MEDIA_CACHE_APP_IMAGES: false
      FIFTYONE_MEDIA_CACHE_SIZE_BYTES: -1
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${FIFTYONE_DEFAULT_APP_ADDRESS}:${FIFTYONE_DEFAULT_APP_PORT}:5151
    restart: always

  teams-api-common:
    image: voxel51/fiftyone-teams-api:v1.6.0
    environment:
      CAS_BASE_URL: ${CAS_BASE_URL}
      FEATURE_FLAG_ENABLE_INVITATIONS: false
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_ENV: ${FIFTYONE_ENV}
      FIFTYONE_INTERNAL_SERVICE: true
      GRAPHQL_DEFAULT_LIMIT: ${GRAPHQL_DEFAULT_LIMIT}
      LOGGING_LEVEL: ${API_LOGGING_LEVEL:-INFO}
      MONGO_DEFAULT_DB: ${FIFTYONE_DATABASE_NAME}
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${API_BIND_ADDRESS}:${API_BIND_PORT}:8000
    restart: always

  teams-app-common:
    image: voxel51/fiftyone-teams-app:v1.6.0
    environment:
      API_URL: ${API_URL}
      APP_USE_HTTPS: ${APP_USE_HTTPS:-true}
      FEATURE_FLAG_ENABLE_INVITATIONS: false
      FIFTYONE_API_URI: ${FIFTYONE_API_URI:-"Please contact your Admin for an API URI"}
      FIFTYONE_APP_ALLOW_MEDIA_EXPORT: ${FIFTYONE_APP_ALLOW_MEDIA_EXPORT:-true}
      FIFTYONE_APP_TEAMS_SDK_RECOMMENDED_VERSION: 0.16.0
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_SERVER_ADDRESS: ""
      FIFTYONE_SERVER_PATH_PREFIX: /api/proxy/fiftyone-teams
      FIFTYONE_TEAMS_PROXY_URL: ${FIFTYONE_TEAMS_PROXY_URL}
      NODE_ENV: production
      RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # GLOBAL_AGENT_HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # GLOBAL_AGENT_HTTP_PROXY: ${HTTP_PROXY_URL}
      # GLOBAL_AGENT_NO_PROXY: ${NO_PROXY_LIST}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # ROARR_LOG: false
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${APP_BIND_ADDRESS}:${APP_BIND_PORT}:3000
    restart: always

  teams-cas-common:
    image: voxel51/fiftyone-teams-cas:v1.6.0
    environment:
      CAS_DATABASE_NAME: ${CAS_DATABASE_NAME}
      CAS_DEFAULT_USER_ROLE: ${CAS_DEFAULT_USER_ROLE}
      CAS_MONGODB_URI: ${CAS_MONGO_DB_URI:-$FIFTYONE_DATABASE_URI}
      CAS_URL: ${BASE_URL}
      DEBUG: ${CAS_DEBUG}
      FIFTYONE_AUTH_MODE: internal
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      NEXTAUTH_URL: ${BASE_URL}/cas/api/auth
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # GLOBAL_AGENT_HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # GLOBAL_AGENT_HTTP_PROXY: ${HTTP_PROXY_URL}
      # GLOBAL_AGENT_NO_PROXY: ${NO_PROXY_LIST}
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # ROARR_LOG: false
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    ports:
      - ${CAS_BIND_ADDRESS}:${CAS_BIND_PORT}:3000
    restart: always

  teams-plugins-common:
    image: voxel51/fiftyone-app:v1.6.0
    environment:
      API_URL: ${API_URL}
      FIFTYONE_AUTH_SECRET: ${FIFTYONE_AUTH_SECRET}
      FIFTYONE_DATABASE_ADMIN: false
      FIFTYONE_DATABASE_NAME: ${FIFTYONE_DATABASE_NAME}
      FIFTYONE_DATABASE_URI: ${FIFTYONE_DATABASE_URI}
      FIFTYONE_DEFAULT_APP_ADDRESS: 0.0.0.0
      FIFTYONE_DEFAULT_APP_PORT: 5151
      FIFTYONE_ENCRYPTION_KEY: ${FIFTYONE_ENCRYPTION_KEY}
      FIFTYONE_INTERNAL_SERVICE: true
      FIFTYONE_MEDIA_CACHE_APP_IMAGES: false
      FIFTYONE_MEDIA_CACHE_SIZE_BYTES: -1
      FIFTYONE_PLUGINS_CACHE_ENABLED: true
      FIFTYONE_PLUGINS_DIR: /opt/plugins
      # If you are routing through a proxy server you will want to set
      #  HTTP_PROXY_URL, HTTPS_PROXY_URL, and NO_PROXY_LIST in your .env
      #  then add the following environment variables to your
      #  `compose.override.yaml`
      # HTTPS_PROXY: ${HTTPS_PROXY_URL}
      # HTTP_PROXY: ${HTTP_PROXY_URL}
      # NO_PROXY: ${NO_PROXY_LIST}
      # http_proxy: ${HTTP_PROXY_URL}
      # https_proxy: ${HTTPS_PROXY_URL}
      # no_proxy: ${NO_PROXY_LIST}
    restart: always
