---
# For Proxy Server instructions please see
#  https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/docker#environment-proxies
services:
  fiftyone-app:
    extends:
      file: ../common-services.yaml
      service: fiftyone-app-common

  teams-api:
    environment:
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    extends:
      file: ../common-services.yaml
      service: teams-api-common
    volumes:
      - plugins-vol:/opt/plugins

  teams-app:
    environment:
      FIFTYONE_TEAMS_PLUGIN_URL: ${FIFTYONE_TEAMS_PLUGIN_URL}
    extends:
      file: ../common-services.yaml
      service: teams-app-common

  teams-cas:
    environment:
      FIFTYONE_AUTH_MODE: internal
      NEXTAUTH_URL: ${BASE_URL}/cas/api/auth
      CAS_URL: ${BASE_URL}
    extends:
      file: ../common-services.yaml
      service: teams-cas-common

  teams-plugins:
    extends:
      file: ../common-services.yaml
      service: teams-plugins-common
    volumes:
      - plugins-vol:/opt/plugins:ro

  telemetry-redis:
    extends:
      file: ../common-services.yaml
      service: telemetry-redis-common

  fiftyone-app-telemetry:
    extends:
      file: ../common-services.yaml
      service: fiftyone-app-telemetry-common
    depends_on:
      fiftyone-app:
        condition: service_started
        restart: true
      telemetry-redis:
        condition: service_started

  teams-api-telemetry:
    extends:
      file: ../common-services.yaml
      service: teams-api-telemetry-common
    depends_on:
      teams-api:
        condition: service_started
        restart: true
      telemetry-redis:
        condition: service_started

  teams-plugins-telemetry:
    extends:
      file: ../common-services.yaml
      service: teams-plugins-telemetry-common
    depends_on:
      teams-plugins:
        condition: service_started
        restart: true
      telemetry-redis:
        condition: service_started

volumes:
  plugins-vol:
  telemetry-redis-data:
