---
# For Proxy Server instructions please see
#  https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/docker#environment-proxies
services:
  fiftyone-app:
    environment:
      FIFTYONE_PLUGINS_CACHE_ENABLED: true
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    extends:
      file: ../common-services.yaml
      service: fiftyone-app-common
    volumes:
      - plugins-vol:/opt/plugins:ro

  teams-api:
    environment:
      FIFTYONE_PLUGINS_DIR: /opt/plugins
    extends:
      file: ../common-services.yaml
      service: teams-api-common
    volumes:
      - plugins-vol:/opt/plugins

  teams-app:
    extends:
      file: ../common-services.yaml
      service: teams-app-common

  teams-cas:
    extends:
      file: ../common-services.yaml
      service: teams-cas-common
    environment:
      CAS_URL: ${AUTH0_BASE_URL}
      NEXTAUTH_URL: ${AUTH0_BASE_URL}/cas/api/auth

  teams-delegated-operator-worker:
    extends:
      file: ../common-services.yaml
      service: teams-delegated-operator-worker-common

volumes:
  plugins-vol:
