---
# For Proxy Server instructions please see
#  https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/docker#environment-proxies
services:
  fiftyone-app:
    extends:
      file: ../common-services.yaml
      service: fiftyone-app-common

  teams-api:
    extends:
      file: ../common-services.yaml
      service: teams-api-common

  teams-app:
    extends:
      file: ../common-services.yaml
      service: teams-app-common

  teams-cas:
    environment:
      CAS_URL: ${AUTH0_BASE_URL}
      NEXTAUTH_URL: ${AUTH0_BASE_URL}/cas/api/auth
    extends:
      file: ../common-services.yaml
      service: teams-cas-common
