apiVersion: v1
kind: Service
metadata:
  {{- with .Values.apiSettings.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "teams-api.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-teams-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiSettings.service.type }}
  ports:
    - port: {{ .Values.apiSettings.service.port }}
      targetPort: {{ .Values.apiSettings.service.shortname }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.apiSettings.service.type "NodePort") (.Values.apiSettings.service.nodePort) }}
      nodePort: {{ .Values.apiSettings.service.nodePort }}
      {{- end }}
  selector:
    {{- include "fiftyone-teams-api.selectorLabels" . | nindent 4 }}
