apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiftyone-teams-api.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-teams-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiSettings.service.type }}
  ports:
    - port: {{ .Values.apiSettings.service.port }}
      targetPort: {{ .Values.apiSettings.service.containerPort | default 8000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "fiftyone-teams-api.selectorLabels" . | nindent 4 }}
