apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiftyone-app.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appSettings.service.type }}
  ports:
    - port: {{ .Values.appSettings.service.port }}
      targetPort: {{ .Values.appSettings.service.containerPort | default 5151 }}
      protocol: TCP
      name: http
  selector:
    {{- include "fiftyone-app.selectorLabels" . | nindent 4 }}
