apiVersion: v1
kind: Service
metadata:
  {{- with .Values.appSettings.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "fiftyone-app.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-app.labels" . | nindent 4 }}
    {{- with .Values.appSettings.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.appSettings.service.type }}
  ports:
    - port: {{ .Values.appSettings.service.port }}
      targetPort: {{ .Values.appSettings.service.shortname }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.appSettings.service.type "NodePort") (.Values.appSettings.service.nodePort) }}
      nodePort: {{ .Values.appSettings.service.nodePort }}
      {{- end }}
  selector:
    {{- include "fiftyone-app.selectorLabels" . | nindent 4 }}
