apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teams-cas.name" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.casSettings.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "fiftyone-teams-cas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.casSettings.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "fiftyone-teams-cas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.casSettings.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fiftyone-teams-cas.selectorLabels" . | nindent 8 }}
        {{- with .Values.casSettings.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fiftyone-teams-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.casSettings.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "teams-cas.name" . }}
          securityContext:
            {{- toYaml .Values.casSettings.securityContext | nindent 12 }}
          image: "{{ .Values.casSettings.image.repository }}:{{ .Values.casSettings.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.casSettings.image.pullPolicy | default "Always" }}
          env:
            {{- include "teams-cas.env-vars-list" . | indent 12 }}
          ports:
            - name: {{ .Values.casSettings.service.shortname }}
              containerPort: {{ .Values.casSettings.service.containerPort | default 3000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /cas/api
              port: {{ .Values.casSettings.service.shortname }}
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /cas/api
              port: {{ .Values.casSettings.service.shortname }}
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /cas/api
              port: {{ .Values.casSettings.service.shortname }}
            failureThreshold: {{ .Values.casSettings.service.startup.failureThreshold }}
            periodSeconds: {{ .Values.casSettings.service.startup.periodSeconds }}
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.casSettings.resources | nindent 12 }}
          volumeMounts:
            {{- range $name := .Values.fiftyoneLicenseSecrets }}
            - name: {{ print $name }}
              mountPath: /opt/fiftyone/licenses
              readOnly: true
            {{- end }}
              {{- with .Values.casSettings.volumeMounts }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
      {{- with .Values.casSettings.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.casSettings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.casSettings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.casSettings.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- include "fiftyone-teams-app.commonTopologySpreadConstraints" (dict "constraints" .Values.casSettings.topologySpreadConstraints "selectorLabels" "fiftyone-teams-cas.selectorLabels" "context" $) | nindent 8 }}
      {{- end }}
      volumes:
        {{- range $name := .Values.fiftyoneLicenseSecrets }}
        - name: {{ print $name }}
          secret:
            secretName: {{ print $name }}
            items:
              - key: license
                path: {{ print $name }}
        {{- end }}
        {{- with .Values.casSettings.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
