{{- if .Values.delegatedOperatorExecutorSettings.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "delegated-operator-executor.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "delegated-operator-executor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.delegatedOperatorExecutorSettings.replicaCount }}
  selector:
    matchLabels:
      {{- include "delegated-operator-executor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.delegatedOperatorExecutorSettings.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "delegated-operator-executor.selectorLabels" . | nindent 8 }}
        {{- with .Values.delegatedOperatorExecutorSettings.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fiftyone-teams-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.delegatedOperatorExecutorSettings.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "delegated-operator-executor.name" . }}
          command: ["fiftyone"]
          args: ["delegated", "launch", "-t", "remote"]
          securityContext:
            {{- toYaml .Values.delegatedOperatorExecutorSettings.securityContext | nindent 12 }}
          image: "{{ .Values.delegatedOperatorExecutorSettings.image.repository }}:{{ .Values.delegatedOperatorExecutorSettings.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.delegatedOperatorExecutorSettings.image.pullPolicy | default "Always" }}
          env:
            {{- include "delegated-operator-executor.env-vars-list" . | indent 12 }}
          resources:
            {{- toYaml .Values.delegatedOperatorExecutorSettings.resources | nindent 12 }}
          {{- with .Values.delegatedOperatorExecutorSettings.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.delegatedOperatorExecutorSettings.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.delegatedOperatorExecutorSettings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.delegatedOperatorExecutorSettings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.delegatedOperatorExecutorSettings.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
