{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fiftyone-teams-app.fullname" . -}}
{{- if .Values.ingress.className }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-teams-app.ingressLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  defaultBackend:
    service:
      name: {{ include "teams-app.name" . }}
      port:
        number: {{ .Values.teamsAppSettings.service.port }}
  {{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.teamsAppSettings.dnsName | quote }}
        {{- if .Values.apiSettings.dnsName }}
        - {{ .Values.apiSettings.dnsName | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.teamsAppSettings.dnsName | quote }}
      http:
        paths:
          {{- if and .Values.ingress.paths (gt (len .Values.ingress.paths) 1) }}
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
          {{- else }}
          - path: {{ .Values.ingress.teamsApp.path }}
            pathType: {{ .Values.ingress.teamsApp.pathType }}
            backend:
              service:
                name: {{ include "teams-app.name" . }}
                port:
                  number: {{ .Values.teamsAppSettings.service.port }}
          {{- end }}
    {{- if .Values.apiSettings.dnsName }}
    - host: {{ .Values.apiSettings.dnsName | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path }}
            pathType: {{ .Values.ingress.api.pathType }}
            backend:
              service:
                name: {{ include "teams-api.name" . }}
                port:
                  number: {{ .Values.apiSettings.service.port }}
    {{- end }}
{{- end }}
