{{- if .Values.pluginsSettings.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.pluginsSettings.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "teams-plugins.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "teams-plugins.labels" . | nindent 4 }}
    {{- with .Values.pluginsSettings.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.pluginsSettings.service.type }}
  ports:
    - port: {{ .Values.pluginsSettings.service.port }}
      targetPort: {{ .Values.pluginsSettings.service.shortname }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.pluginsSettings.service.type "NodePort") (.Values.pluginsSettings.service.nodePort) }}
      nodePort: {{ .Values.pluginsSettings.service.nodePort }}
      {{- end }}
  selector:
    {{- include "teams-plugins.selectorLabels" . | nindent 4 }}
{{- end }}
