{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-teams-app.secretLabels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.fiftyone }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end -}}
{{- end }}
