{{- if .Values.teamsAppSettings.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "teams-app.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "teams-app.labels" . | nindent 4 }}
    {{- with .Values.teamsAppSettings.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.teamsAppSettings.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.teamsAppSettings.podDisruptionBudget.minAvailable }}
  {{- else if .Values.teamsAppSettings.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.teamsAppSettings.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  {{- fail "You must set either 'minAvailable' or 'maxUnavailable' for the PodDisruptionBudget." }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teams-app.selectorLabels" . | nindent 6 }}
{{- end }}
