apiVersion: v1
kind: Service
metadata:
  {{- with .Values.teamsAppSettings.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "teams-app.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "teams-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.teamsAppSettings.service.type }}
  ports:
    - port: {{ .Values.teamsAppSettings.service.port }}
      targetPort: {{ .Values.teamsAppSettings.service.shortname }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.teamsAppSettings.service.type "NodePort") (.Values.teamsAppSettings.service.nodePort) }}
      nodePort: {{ .Values.teamsAppSettings.service.nodePort }}
      {{- end }}
  selector:
    {{- include "teams-app.selectorLabels" . | nindent 4 }}
