apiVersion: v1
kind: Service
metadata:
  name: {{ include "teams-app.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fiftyone-teams-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.teamsAppSettings.service.type }}
  ports:
    - port: {{ .Values.teamsAppSettings.service.port }}
      targetPort: {{ .Values.teamsAppSettings.service.containerPort | default 3000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "fiftyone-teams-app.selectorLabels" . | nindent 4 }}
