apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teams-app.name" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.teamsAppSettings.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "teams-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.teamsAppSettings.autoscaling.enabled }}
  replicas: {{ .Values.teamsAppSettings.replicaCount | default 2 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teams-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.teamsAppSettings.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "teams-app.selectorLabels" . | nindent 8 }}
        {{- with .Values.teamsAppSettings.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fiftyone-teams-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.teamsAppSettings.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "teams-app.name" . }}
          securityContext:
            {{- toYaml .Values.teamsAppSettings.securityContext | nindent 12 }}
          image: "{{ .Values.teamsAppSettings.image.repository }}:{{ .Values.teamsAppSettings.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.teamsAppSettings.image.pullPolicy | default "Always" }}
          env:
            {{- include "fiftyone-teams-app.env-vars-list" . | indent 12 }}
          ports:
            - name: {{ .Values.teamsAppSettings.service.shortname }}
              containerPort: {{ .Values.teamsAppSettings.service.containerPort | default 3000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/hello
              port: {{ .Values.teamsAppSettings.service.shortname }}
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/hello
              port: {{ .Values.teamsAppSettings.service.shortname }}
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /api/hello
              port: {{ .Values.teamsAppSettings.service.shortname }}
            failureThreshold: {{ .Values.teamsAppSettings.service.startup.failureThreshold }}
            periodSeconds: {{ .Values.teamsAppSettings.service.startup.periodSeconds }}
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.teamsAppSettings.resources | nindent 12 }}
          {{- with .Values.teamsAppSettings.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.teamsAppSettings.initContainers.enabled }}
      initContainers:
        {{-
          include "fiftyone-teams-app.commonInitContainers"
          (dict "repository" .Values.teamsAppSettings.initContainers.image.repository "tag" .Values.teamsAppSettings.initContainers.image.tag "casServiceName" (include "teams-cas.name" .) )
          | nindent 8
        }}
      {{- end }}
      {{- with .Values.teamsAppSettings.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.teamsAppSettings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.teamsAppSettings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.teamsAppSettings.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- include "fiftyone-teams-app.commonTopologySpreadConstraints" (dict "constraints" .Values.teamsAppSettings.topologySpreadConstraints "selectorLabels" "teams-app.selectorLabels" "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.teamsAppSettings.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
