{{- if and .Values.telemetry.enabled (not .Values.telemetry.redis.external.url) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry.redis.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "telemetry.redis.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "telemetry.redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
