# Voxel51 provided you with a voxel51-docker.json file, you can use the following command to create a Pull Secret:
#  kubectl --namespace your-namespace-here create secret generic regcred \
#    --from-file=.dockerconfigjson=./voxel51-docker.json --type kubernetes.io/dockerconfigjson
# If you use the Voxel51 command above your imagePullSecrets would look like:
imagePullSecrets:
 - name: regcred

secret:
  fiftyone:
    # These secrets come from Voxel51
    apiClientId:
    apiClientSecret:
    auth0Domain:
    clientId:
    clientSecret:
    organizationId:
    # These secrets come from your MongoDB implementation
    fiftyoneDatabaseName: fiftyone
    mongodbConnectionString: mongodb://admin:REPLACEME@fiftyone-mongodb.fiftyone-mongodb.svc.cluster.local/?authSource=admin
    # This secret is a required random string used to encrypt session cookies
    # Use something like `openssl rand -hex 32` to generate this string
    cookieSecret:

#apiSettings:

# appSettings:
#   env:
#     GOOGLE_APPLICATION_CREDENTIALS: /opt/secrets/google/service-account
#   volumes:
#     - name: google-credentials-volume
#       secret:
#         secretName: google-credentials-secret
#         optional: false
#   volumeMounts:
#     - mountPath: /opt/secrets/google
#       name: google-credentials-volume

teamsAppSettings:
  dnsName: replace.this.dns.name

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.global-static-ip-name: "fiftyone-teams-static-ip"
