# Voxel51 provided you with a voxel51-docker.json file, you can use the following command to create a Pull Secret:
#  kubectl --namespace your-namespace-here create secret generic regcred \
#    --from-file=.dockerconfigjson=./voxel51-docker.json --type kubernetes.io/dockerconfigjson
# If you use the Voxel51 command above your imagePullSecrets would look like:
# imagePullSecrets:
#  - name: regcred

secret:
  fiftyone:
    # These secrets come from Voxel51
    apiClientId:
    apiClientSecret:
    auth0Domain:
    clientId:
    clientSecret:
    organizationId:
    # These secrets come from your MongoDB implementation
    fiftyoneDatabaseName: fiftyone
    mongodbConnectionString: mongodb://username:password@somehostname/?authSource=admin
    # This secret is a required random string used to encrypt session cookies
    # Use something like `openssl rand -hex 32` to generate this string
    cookieSecret:

# apiSettings:

# If you are performing an initial install you should either connect to your database with the SDK first or
#   set FIFTYONE_DATABASE_ADMIN to true.  We highly recommend setting this to false during normal operations
#   to prevent upgrading dataset versions before new SDKs have been deployed.
#   https://helm.fiftyone.ai/#installation-considerations
# appSettings:
#   env:
#     FIFTYONE_DATABASE_ADMIN: true

teamsAppSettings:
  dnsName: teams-upgrade.dev.fiftyone.ai

# ingress:
#   annotations:
