# Voxel51 provided you with a voxel51-docker.json file, you can use the following command to create a Pull Secret:
#  kubectl --namespace your-namespace-here create secret generic regcred \
#    --from-file=.dockerconfigjson=./voxel51-docker.json --type kubernetes.io/dockerconfigjson
# If you use the Voxel51 command above your imagePullSecrets would look like:
# imagePullSecrets:
#  - name: regcred

secret:
  fiftyone:
    # These secrets come from Voxel51
    apiClientId:
    apiClientSecret:
    auth0Domain:
    clientId:
    clientSecret:
    organizationId:
    # These secrets come from your MongoDB implementation
    fiftyoneDatabaseName: fiftyone
    mongodbConnectionString: mongodb://username:password@somehostname/?authSource=admin
    # This secret is a required random string used to encrypt session cookies
    # Use something like `openssl rand -hex 32` to generate this string
    cookieSecret:
    # This key is required and is used to encrypt storage credentials in the MongoDB
    #   do NOT lose this key!
    # generate keys by executing the following in python:
    #
    # from cryptography.fernet import Fernet
    # print(Fernet.generate_key().decode())
    encryptionKey:

# apiSettings:

appSettings:
 env:
   # This value is set to `true` by default for v1.1.0 installs as v1.1.0 is not backwards
   #  compatible with previous versions.
   FIFTYONE_DATABASE_ADMIN: true

teamsAppSettings:
  dnsName: teams-upgrade.dev.fiftyone.ai

# ingress:
#   annotations:
