---
# # Voxel51 provided you with a voxel51-docker.json file, you can use the following command to create a Pull Secret:
# #
# # ```shell
# #  kubectl --namespace your-namespace-here create secret generic regcred \
# #    --from-file=.dockerconfigjson=./voxel51-docker.json --type kubernetes.io/dockerconfigjson
# # ```
# #
# # If you use the Voxel51 command above your imagePullSecrets would look like:
# imagePullSecrets:
#   - name: regcred

secret:
  fiftyone:
    # Voxel51 provides these secrets
    apiClientId:
    apiClientSecret:
    auth0Domain:
    clientId:
    clientSecret:
    organizationId:

    # These secrets come from your MongoDB implementation
    fiftyoneDatabaseName: fiftyone
    mongodbConnectionString: mongodb://username:password@somehostname/?authSource=admin

    # This secret is a required random string used to encrypt session cookies.
    # To generate this string, run
    #
    # ```shell
    # openssl rand -hex 32
    # ````
    #
    cookieSecret:

    # This required key is used to encrypt storage credentials in the database.
    #   Do NOT lose this key!
    # To generate this key, run (in python)
    #
    # ```python
    # from cryptography.fernet import Fernet
    # print(Fernet.generate_key().decode())
    # ```
    #
    encryptionKey:

# apiSettings:
#   # Set `dnsName` to expose the API for host-based routing only.
#   # See https://helm.fiftyone.ai/docs/expose-teams-api.html for more information.
#   dnsName: your-api.hostname.here
#   env:
#     # Set FIFTYONE_PLUGINS_DIR if you are enabling plugins in a dedicated `teams-plugins` deployment
#     # See https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/helm#enabling-fiftyone-teams-plugins
#     FIFTYONE_PLUGINS_DIR: /opt/plugins
#     Set FIFTYONE_TEAMS_VERSION_OVERRIDE to override the `Install FiftyOne`
#       bash command in the `Settings > Install FiftyOne` modal
#     FIFTYONE_TEAMS_VERSION_OVERRIDE: pip install --index-url https://privatepypi.internal.org fiftyone==0.15.9


appSettings:
  env:
    # When performing a new install, use this override.
    # After the initial installation, remove this value to use the Chart's default value `false.`
    # Please see https://helm.fiftyone.ai/#initial-installation-vs-upgrades for details.
    FIFTYONE_DATABASE_ADMIN: true
    # Set FIFTYONE_PLUGINS_DIR and FIFTYONE_PLUGINS_CACHE_ENABLED
    # when enabling plugins in the `fiftyone-app` deployment
    # See https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/helm#enabling-fiftyone-teams-plugins
    # FIFTYONE_PLUGINS_DIR: /opt/plugins
    # FIFTYONE_PLUGINS_CACHE_ENABLED: true

# pluginsSettings:
#   enabled: true
#   env:
#     # Set FIFTYONE_PLUGINS_DIR and FIFTYONE_PLUGINS_CACHE_ENABLED
#     # when enabling plugins in a dedicated `teams-plugins` deployment.
#     # See https://github.com/voxel51/fiftyone-teams-app-deploy/tree/main/helm#enabling-fiftyone-teams-plugins
#     FIFTYONE_PLUGINS_DIR: /opt/plugins
#     FIFTYONE_PLUGINS_CACHE_ENABLED: true

teamsAppSettings:
  dnsName: your.hostname.here

# ingress:
#   annotations:
