# Voxel51 provided you with a voxel51-docker.json file, you can use the following command to create a Pull Secret:
#  kubectl --namespace your-namespace-here create secret generic regcred \
#    --from-file=.dockerconfigjson=./voxel51-docker.json --type kubernetes.io/dockerconfigjson
# If you use the Voxel51 command above your imagePullSecrets would look like:
# imagePullSecrets:
#  - name: regcred

secret:
  fiftyone:
    # These secrets come from Voxel51
    apiClientId:
    apiClientSecret:
    auth0Domain:
    clientId:
    clientSecret:
    organizationId:
    # These secrets come from your MongoDB implementation
    fiftyoneDatabaseName: fiftyone
    mongodbConnectionString: mongodb://username:password@somehostname/?authSource=admin
    # This secret is a required random string used to encrypt session cookies
    # Use something like `openssl rand -hex 32` to generate this string
    cookieSecret:
    # This key is required and is used to encrypt storage credentials in the MongoDB
    #   do NOT lose this key!
    # generate keys by executing the following in python:
    #
    # from cryptography.fernet import Fernet
    # print(Fernet.generate_key().decode())
    encryptionKey:

# apiSettings:

appSettings:
 env:
   # FIFTYONE_DATABASE_ADMIN is set to `false` by default for v1.2.1 installs
   #  If you are performing a new install or an upgrade from v1.0 or earlier you may want to set
   #  this value to `true`.
   #  Please see https://helm.fiftyone.ai/#initial-installation-vs-upgrades for details
   # FIFTYONE_DATABASE_ADMIN: false

teamsAppSettings:
  dnsName: teams-upgrade.dev.fiftyone.ai

# ingress:
#   annotations:
