name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  modified-files:
    runs-on: ubuntu-latest
    outputs:
      docker-unit-required: ${{ steps.filter.outputs.docker-unit }}
      helm-integration-required: ${{ steps.filter.outputs.helm-integration }}
      helm-unit-required: ${{ steps.filter.outputs.helm-unit }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker-unit:
              - '.github/workflows/test-docker.yml'
              - 'docker/common-services.yaml'
              - 'docker/internal-auth/**'
              - 'docker/legacy-auth/**'
              - 'tests/fixtures/docker/**'
              - 'tests/integration/compose/**'
              - 'tests/unit/compose/**'
            helm-integration:
              - '.github/workflows/test-integration-helm.yml'
              - 'helm/fiftyone-teams-app/**'
              - 'tests/fixtures/helm/**'
              - 'tests/integration/helm/**'
              - 'tests/unit/helm/**'
            helm-unit:
              - '.github/workflows/test-helm.yml'
              - 'helm/fiftyone-teams-app/**'
              - 'tests/fixtures/helm/**'
              - 'tests/integration/helm/**'
              - 'tests/unit/helm/**'

  docker-unit:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.docker-unit-required == 'true' }}
    uses: ./.github/workflows/test-docker.yml

  helm-integration:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.helm-integration-required == 'true' }}
    uses: ./.github/workflows/test-integration-helm.yml

  helm-unit:
    needs: modified-files
    if: ${{ needs.modified-files.outputs.helm-unit-required == 'true' }}
    uses: ./.github/workflows/test-helm.yml

  all-tests:
    runs-on: ubuntu-latest
    needs: [docker-unit, helm-unit, helm-integration]
    if: always()
    steps:
      - run: sh -c ${{
          (needs.docker-unit.result == 'success' || needs.docker-unit.result == 'skipped') &&
          (needs.helm-integration.result == 'success' || needs.helm-integration.result == 'skipped') &&
          (needs.helm-unit.result == 'success' || needs.helm-unit.result == 'skipped') }}

  helm-pre-release:
    needs: [all-tests, helm-unit, helm-integration]
    if: |
      always() &&
      (needs.helm-unit.result == 'success' || needs.helm-integration.result == 'success')
    uses: ./.github/workflows/pre-release-internal-env.yml
