---
name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
      - name: Temporary SQLite/LZMA - Install missing libraries
        run: sudo apt install -y libsqlite3-dev libbz2-dev
      - name: install asdf & tools
        uses: asdf-vm/actions/install@v3.0.2
        with:
          # Issue with some of the pre-commit hooks. So pin to an older version for now. See
          # https://github.com/voxel51/fiftyone-teams-app-deploy/actions/runs/13078221229/job/36495530561
          # See https://voxel51.atlassian.net/browse/AS-506
          asdf_branch: v0.14.1
      - uses: pre-commit/action@v3.0.1
