name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: install asdf & tools
        uses: asdf-vm/actions/install@v3.0.2
      - uses: pre-commit/action@v3.0.1
