---
name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6.2.0
      - name: Temporary SQLite/LZMA - Install missing libraries
        run: sudo apt install -y libsqlite3-dev libbz2-dev
      - name: Install asdf & tools
        uses: "voxel51/aloha-github-workflows/.github/actions/asdf-install-and-cache@main"
      - name: Install helm plugins
        run: make helm-plugins
      - uses: pre-commit/action@v3.0.1
