---
name: Release Charts

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      changed_charts: ${{ steps.chart_releaser.outputs.changed_charts }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Run chart-releaser
        id: chart_releaser
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
          CR_SKIP_EXISTING: true
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm


  update-chart-version:
    if: ${{ needs.release.outputs.changed_charts != '' }}
    needs: release
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get Chart Version
        id: get-version
        run: |
          version=$(yq ".version" helm/fiftyone-teams-app/Chart.yaml)
          echo "FIFTYONE_TEAMS_APP_DEPLOY_VERSION=${version}" >> "${GITHUB_ENV}"
          echo "FIFTYONE_TEAMS_APP_DEPLOY_VERSION=${version}" >> "${GITHUB_OUTPUT}"

      - name: Trigger Internal Chart Build by Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CROSS_REPOSITORY_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: "${{ secrets.CROSS_REPOSITORY_REPOSITORY }}",
              workflow_id: "${{ secrets.CROSS_REPOSITORY_WORKFLOW_2 }}",
              ref: "main",
              inputs: {
                "fiftyone-teams-app-deploy-version": "${{ steps.get-version.outputs.FIFTYONE_TEAMS_APP_DEPLOY_VERSION }}"
              }
            })
