---
name: Tests - Docker Compose

on:
  workflow_call:
    secrets:
      REPO_GOOGLE_WORKLOAD_IDP:
        required: true
      FO_INTERNAL_LICENSE:
        required: true
      FO_LEGACY_LICENSE:
        required: true

jobs:
  unit-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6.0.0
      - name: install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0
      - name: Run unit tests
        shell: bash
        run: |
          make test-unit-compose
  integration-compose-internal:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6.0.0
      - name: Temporary SQLite/LZMA - Install missing libraries
        run: sudo apt install -y libsqlite3-dev libbz2-dev
      - name: install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.7
        with:
          project_id: 'computer-vision-team'
          service_account: 'github@computer-vision-team.iam.gserviceaccount.com'
          token_format: access_token
          workload_identity_provider: ${{ secrets.REPO_GOOGLE_WORKLOAD_IDP }}
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Login to GAR
        uses: docker/login-action@v3.4.0
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Create Local License From Secret
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.FO_INTERNAL_LICENSE }}
          filename: 'internal-license.key'
          is-executable: false
          working-directory: './docker'
      - name: Run compose integration tests for internal
        shell: bash
        run: |
          make test-integration-compose-internal
  integration-compose-legacy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6.0.0
      - name: install asdf & tools
        uses: asdf-vm/actions/install@v4.0.0
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.7
        with:
          project_id: 'computer-vision-team'
          service_account: 'github@computer-vision-team.iam.gserviceaccount.com'
          token_format: access_token
          workload_identity_provider: ${{ secrets.REPO_GOOGLE_WORKLOAD_IDP }}
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Login to GAR
        uses: docker/login-action@v3.4.0
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Create Local License From Secret
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.FO_LEGACY_LICENSE }}
          filename: 'legacy-license.key'
          is-executable: false
          working-directory: './docker'
      - name: Run compose integration tests for legacy
        shell: bash
        run: |
          make test-integration-compose-legacy
