---
name: Tests - Integration Helm

on:
  workflow_call:
    secrets:
      ORG_RO_ALOHA_GITHUB_WORKFLOWS_FG_PAT:
        required: true
      REPO_GOOGLE_WORKLOAD_IDP:
        required: true

jobs:
  integration-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v6
      - name: Checkout voxel51/aloha-github-workflows
        uses: actions/checkout@v6
        with:
          repository: voxel51/aloha-github-workflows
          ref: main
          token: ${{ secrets.ORG_RO_ALOHA_GITHUB_WORKFLOWS_FG_PAT }}
          path: ./.github/actions/aloha-github-workflows
      - name: Set generate-version-file action's path from remote to local
        # Public repos cannot access private action repo without GitHub Enterprise
        # Instead, we clone the private workflow directory and update the `asdf-install-and-cache/action.yml`
        # file's reference to `voxel51/aloha-github-workflows/.github/actions/generate-version-file` with the local path.
        shell: bash
        run: |
          sed -i \
            's%voxel51/aloha-github-workflows/.github/actions/generate-version-file@main%./.github/actions/aloha-github-workflows/.github/actions/generate-version-file%' \
            .github/actions/aloha-github-workflows/.github/actions/asdf-install-and-cache/action.yml
      - uses: actions/setup-python@v6.2.0
      - name: Temporary SQLite/LZMA - Install missing libraries
        run: sudo apt install -y libsqlite3-dev libbz2-dev
      - name: Install asdf & tools
        uses: ./.github/actions/aloha-github-workflows/.github/actions/asdf-install-and-cache
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: 'computer-vision-team'
          service_account: 'github@computer-vision-team.iam.gserviceaccount.com'
          workload_identity_provider: ${{ secrets.REPO_GOOGLE_WORKLOAD_IDP }}
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
      - name: Run integration tests
        shell: bash
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          make helm-repos
          make test-integration-helm-ci
